import Head from 'next/head';
import { useRouter } from 'next/router';
import { FC, ReactNode, useEffect } from 'react';
import { scroller } from 'react-scroll';

import Footer from '../Footer';
import Header from '../Header';

import style from './Layout.module.scss';

interface LayoutProps {
  children: ReactNode;
  title?: string;
}

const Layout: FC<LayoutProps> = ({
  children,
  title = 'Оценка продолжительности совместной жизни с вашим партнером',
}) => {
  const router = useRouter();

  useEffect(() => {
    const sectionName = router.asPath.split('#')[1];
    if (!sectionName) return;

    const headerElement = document.getElementsByTagName('header')[0]?.clientHeight;

    scroller.scrollTo(sectionName, {
      duration: 0,
      delay: 0,
      smooth: true,
      offset: headerElement ? -headerElement : 0,
    });
  }, [router.asPath]);

  return (
    <div className={style.content}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        {children}
      </main>
      <Footer />
    </div>
  );
};

export default Layout;
