import Head from 'next/head';
import { FC, ReactNode } from 'react';

import Footer from '../Footer';
import Header from '../Header';

import style from './Layout.module.scss';

interface LayoutProps {
  children: ReactNode;
  title?: string;
}

const Layout: FC<LayoutProps> = ({
  children,
  title = 'Оценка продолжительности совместной жизни с вашим партнером',
}) => (
  <div className={style.content}>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    <main>
      {children}
    </main>
    <Footer />
  </div>
);

export default Layout;
