import Head from 'next/head';
import { FC, ReactNode } from 'react';

import Footer from './Footer';
import Header from './Header';

interface LayoutProps {
  children: ReactNode;
  title?: string;
}

const Layout: FC<LayoutProps> = ({
  children,
  title = 'Оценка продолжительности совместной жизни с вашим партнером',
}) => (
  <>
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />
    {children}
    <Footer />
  </>
);

export default Layout;
